#! /bin/bash
# Takes a list of files from STDIN and executes the command specified on change

if [ ! -n "$1" ]; then
    echo "Usage: watchfiles command"
    exit 1
fi

# `ls` is different on OSX and Linux
lsargs='-lT'
if [ -d /proc ]; then
    lsargs='-l --full-time'
fi

while read watchfile; do
    files="$files $watchfile"
done

while sleep .5; do
    contents=$(ls $lsargs $files)
    if [ "$contents" != "$old_contents" ]; then
        old_contents=$contents
        eval "$*"
    fi
done
