#! /bin/bash
# Takes a list of files from STDIN and executes the command specified on change

if [ ! -n "$1" ]; then
    echo "Usage: watchfiles command"
    exit 1
fi

while read watchfile; do
    files="$files $watchfile"
done

while sleep .5; do
    contents=$(ls -lT $files)
    if [ "$contents" != "$old_contents" ]; then
        old_contents=$contents
        eval "$*"
    fi
done
