#! /bin/bash
# Takes a list of files from STDIN and executes the command specified on change

if [ ! -n "$1" ]; then
    echo "Usage: watchfiles command"
    exit 1
fi

curdir=`pwd`
curdir=${curdir//\//.}
dirfile="/tmp/$curdir"

cmd="$1"
shift
args="$@"

while read watchfile; do
    files="$files $watchfile"
done

while sleep .5; do
    contents=$(ls -lT $files)
    if [ ! -e $dirfile ] ||
        ! diff -q <(cat $dirfile) <(echo $contents) > /dev/null
    then
        echo $contents > $dirfile
        $cmd $args
    fi
done
